config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :categories
  resources :posts
  resources :posts do
    resources :comments
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
        can :manage, Post, user_id: user.id
        #can :manage, Comment, user_id: user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  validates :commentable, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  mount_uploader :featured, ImageUploader
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render "new"
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
      render json: @category.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :slug)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @commentable = find_commentable
    @comments = @commentable.comments
  end
  def update
  end
  def create
    @commentable = find_commentable
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(params[:post_id])
    else
      flash.now[:danger] = "error"
    end
  end
  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
  end
  private
    def find_commentable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
      end
    end

    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    if params[:category].present?
      @category = Category.find(params[:category])
      @posts = @category.posts
    else
      @posts = Post.all
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render "new"
    end
  end

  def update
    @post.user = current_user
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to post_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id, :user_id, :featured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/application/_comments.html.haml
%div
  %hr
  %div{:class => "comments"}
    = render commentable.comments
  %div
  = form_for [commentable, commentable.comments.build], remote: true do |f|
    %div{:class => "form-group"}
      = f.cktext_area :body, class: 'ckeditor', id: 'ckeditor'
      = f.submit '댓글 쓰기', class: 'btn btn-default'

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field
    = f.label :slug
    = f.text_field :slug, class: "form-control"
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table.table.table-stripe
  %thead
    %tr
      %th Name
      %th Slug
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.slug
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Category', new_category_path, class: "btn btn-default"
= link_to 'Home', root_path, class: "btn btn-default"

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path, class: "btn btn-default"

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Slug:
  = @category.slug

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/comments/_comment.html.haml
= content_tag_for :div, comment do
  %div
    = comment.user.email if comment.user
  %div
    = raw comment.body

app/views/home/_header.html.haml
/ Fixed navbar
.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Blog
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to "Home", root_path
        %li
          = link_to "Posts", posts_path
        %li
          = link_to 'Categories', categories_path
        %li
          %a{:href => "#about"} About
        %li
          %a{:href => "#contact"} Contact
        - if user_signed_in?
          %li
            %a{:href => "#"}
              = current_user.email
          %li
            = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Sign in', new_user_session_path
          %li
            = link_to 'Sign up', new_user_registration_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Dropdown
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li.dropdown-header Nav header
            %li
              %a{:href => "#"} Separated link
            %li
              %a{:href => "#"} One more separated link
    / /.nav-collapse

app/views/home/index.html.haml
.page-container.container
  = yield
  .jumbotron
    .container
      %h1.display-3 ROR 101 Tutorial!
      %p 빠띠의 ROR 101 Tutorial 입니다.
  - if user_signed_in?
    = "Hello! " + current_user.email
    = link_to 'Sign out', destroy_user_session_path, method: :delete
  - else
    = link_to 'Sign in', new_user_session_path
    = link_to 'Sign up', new_user_registration_path

  %h3 This Tutorial have...
  .row
    .col-sm-4
      %h4 카테고리 편집
      %a.btn.btn-info{href: "#", role: "button"} View details »
    .col-sm-4
      %h4 포스트 편집
      %a.btn.btn-info{href: "#", role: "button"} View details »
    .col-sm-4
      %h4 로그인, 로그아웃
      %a.btn.btn-info{href: "#", role: "button"} View details »

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog1
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag Ckeditor.cdn_url
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
  %body
    = render 'home/header'
    .page-container.container
      = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field.emoji-picker-container
    = f.label :body
    = f.cktext_area :body, id: 'ckeditor', data: { emojiable: true }
  .field
    = f.label :category
    = f.collection_select :category_id, Category.all, :id, :name, include_blank: true
  .field
    = f.label :featured, '이미지'
    = f.file_field :featured
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

- if @category
  %h3= @category.name + ' 카테고리 포스트를 보여줍니다.'

.row
  .col-sm-2.col-sm-offset-10
    = form_tag posts_path(category: :category), method: "get" do
      .field
        = label_tag "Select Category"
        - if @category
          = select_tag :category, options_from_collection_for_select(Category.all, :id, :name, selected: @category.id), class: "form-control", onchange: "this.form.submit();", :prompt => "category"
        - else
          = select_tag :category, options_from_collection_for_select(Category.all, :id, :name), class: "form-control", onchange: "this.form.submit();", :prompt => "category"

%table.table.table-hover
  %thead.thead-dark
    %tr
      %th.col-xs-3{scope: "col"} Title
      %th.col-xs-3{scope: "col"} Category
      %th.col-xs-3{scope: "col"} User
      %th.col-xs-3{scope: "col"} Edit/Destroy

  %tbody
    - @posts.each do |post|
      %tr
        %td.col-xs-3= link_to post.title, post
        %td.col-xs-3= post.category.name
        %td.col-xs-3= post.user.email if post.user_id?
        %td.col-xs-3
          = link_to 'Edit', edit_post_path(post), class: "btn btn-default" if can? :edit, post
          = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" if can? :edit, post

%br

- if user_signed_in?
  = link_to 'New Post', new_post_path , class: "btn btn-default"
- if @category
  = link_to 'List All', posts_path, class: "btn btn-default"
= link_to 'Home', root_path, class: "btn btn-default"

app/views/posts/new.html.haml
%h1 New Post
= render 'form'

= link_to 'Back', posts_path, class: "btn btn-default"

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Category:
  = @post.category.name
%p
  %b Title:
  = @post.title
%p
  %b Body:
  = raw @post.body

%p
  %b Image:
  = image_tag @post.featured_url(:thumb) if @post.featured?

= link_to 'Edit', edit_post_path(@post), class: "btn btn-default"
= link_to 'Back', posts_path, class: "btn btn-default"

%p
  %b
    Comments
    = render "comments", commentable: @post